### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by dseeva** [lakhank295/homebridge-inception-panel#1]
Hi, getting an error with this plugin, any ideas?
i know nothing about js.
Thanks!!

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/homebridge-inception/index.js:71:22)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-inception/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-inception/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-inception/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)

**Comment by dseeva** [comment]
Please ignore, i had included my area_id/activity at the end, removing that fixed the issue, it works great now, thank you!!
